### ISSUE TITLE
Como Instalar y configurar emulador de PSP (ppsspp)

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#11]
**Como instalar emulador de PSP (ppsspp)**
En primer lugar abrimos un ventana de terminal y lanzamos el script de instalacion:
/opt/RGBux/installers/ppsspp.sh

Una vez terminada , llevará un rato, vamos a proceder a modificar el lanzador de psp, que no es correcto, se encuentra en la ruta /opt/RGBux/frontend/launchers
El archivo está nombrado como "lanzadorPSP.sh" lo editamos con mousepad, y lo dejamos asi:

---
```
#!/bin/bash

################################################################################
#                                                                              #
################################################################################

# Config video no necesaria se encarga 15khz-switchres-exec

# Genera la variable CORE y los CFGs
. /opt/RGBux/bin/launcher-ra-init


exec /opt/RGBux/bin/15khz-switchres-exec 720 480 60 /usr/games/PPSSPPQt --fullscreen --escape-exit "$@"
```

---

# Comandos para el inicio de ppsspp

--state= // Set path to savestate which should be loaded

--escape-exit  // Exits emulator instead of exiting to pause menu

--pause-menu-exit // Similar to earlier one, but exits emulator from pause menu instead exiting just the game

--fullscreen // Forces launch in fs

**Comment by DSkywalk** [comment]
@sirmagb00 esto sigue siendo necesario?
