### ISSUE TITLE
Como preparar un disco para instalar RGBUX

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#12]
Si disponemos de un disco mayor de 2 tb, debemos preparar las particiones del disco, para ellos vamos a usar gparted live, lo podemos descargar desde nuestro grupo RGB-uX Soporte.
Es una imagen iso, la grabamos en un pendrive con Rufus, o balena.
Una vez arrancado Gparted , y partiendo que tenemos un disco grande , en este ejemplo voy a usar uno de 2 Tb. En primer lugar vamos a proceder a hacer una particion de 500 mbs, una partición primaria, esta partición debe estar formateada con el sistema de archivos "fat32":
![photo_2019-08-03_23-20-09](https://user-images.githubusercontent.com/51505710/62417098-d55bb080-b647-11e9-9903-07883b5c8f22.jpg)

A continuación cogemos el resto de espacio del disco y creamos una partición extendida:
![photo_2019-08-03_23-23-10](https://user-images.githubusercontent.com/51505710/62417027-e7d4ea80-b645-11e9-9c31-e23a82708ef3.jpg)
Ahora en el espacio sin asignar , vamos a crear una partición que albergará los saves de nuestros juegos, con un espacion de por ejemplo 15 gigas es mas que sucifiente, como se puede ver en la siguiente captura, es una partición logica con formato de archivos ext4:
![photo_2019-08-03_23-26-40](https://user-images.githubusercontent.com/51505710/62417037-5ade6100-b646-11e9-913e-daaf33aa2441.jpg)
Ahora vamos a crear otra partición logica que va a ser sobre la que se va a instalar el sistema, he pensado en una tamaño de 60 gigas, ( va por encima de lo necesario) partición logica con formato ext4:
![photo_2019-08-03_23-28-10](https://user-images.githubusercontent.com/51505710/62417049-ab55be80-b646-11e9-95d2-9e2b1160aa95.jpg)
Y en el espacio que nos queda por asignar que será el mayor, un giga y pico, en el ejemplo, creamos la última partición logica,con formato ext4, asignandole todo el tamaño libre del que disponemos, sobre esta partición se copiarán todos los packs de juegos.
A modo ilustrativo, así es como queda finalmente la configuración de las particiones:
![photo_2019-08-03_23-34-01](https://user-images.githubusercontent.com/51505710/62417071-4babe300-b647-11e9-875e-a1550879472b.jpg)

**Comment by DSkywalk** [comment]
ahora en https://github.com/rgb-x/system/wiki/Como-preparar-un-disco-para-RGBux-(es)
