### ISSUE TITLE
Guia de Instalacion de RGB-uX

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#13]
En primer lugar descargamos la iso de nuestra RC4b, esta disponible desde varias plataformas, podeis elegir la que querais. Una vez descargada la grabais en un pendrive, ya sea con Rufus o con Balena.Debemos conectar el PC, a un monitor de 31 khz (un monitor plano).
En el arranque del PC, se puede elegir desde las opciones de boot de la placa base, si queremos un arranque Legacy o Uefi. Cualquiera de los dos son validos. Yo escojo en este ejemplo, el arranque uefi:

![arranque pc uefi](https://user-images.githubusercontent.com/51505710/62419693-c21c0580-b686-11e9-9797-93639d23d197.jpg)
El pendrive , es el kingston data traveler. Despues va a cargar el siguiente menu:
![menu de rgbux live](https://user-images.githubusercontent.com/51505710/62419700-00192980-b687-11e9-8034-fc4e26669f41.jpg)
Escogemos la opción Install 31 khz. Va a cargar una serie de archivos, y nos pregunta que puerto vamos a usar con RGBux:
![elegir puerto](https://user-images.githubusercontent.com/51505710/62419721-7f0e6200-b687-11e9-97ce-8c269c6eed51.jpg)
En el ejemplo, se selecciona el puerto DVI -I, que se encuentra desconectado, en la imagen se ve el puerto que se encuentra conectado que es el HDMI. Nos va a indicar que puerto hemos escogido:
![puerto seleccionado](https://user-images.githubusercontent.com/51505710/62419734-d6accd80-b687-11e9-82dc-bafda3ef6b31.jpg)
Al pulsar en ok, nos configura el puerto:
![puerto configurado](https://user-images.githubusercontent.com/51505710/62419737-f04e1500-b687-11e9-9e0a-5586c3c45fba.jpg)
Al pulsar a ok nos lleva a esta pantalla donde hay que pulsar en instalar sistema:
![introducir contraseñas](https://user-images.githubusercontent.com/51505710/62419743-0f4ca700-b688-11e9-903a-42c157680e58.jpg)
![introducir contraseñas 3](https://user-images.githubusercontent.com/51505710/62419749-3c995500-b688-11e9-82e3-ca9047c1d161.jpg)
Nos pregunta por las contraseñas que vamos a utilizar, podeis poner las que querais.
En el siguiente paso debemos configurar nuestro disco duro. Debemos establecer los puntos de montaje, de cada partición. Si no tienes el disco duro correctamente particionado, hay una guia de como hacer las particiones aqui: https://github.com/rgb-x/system/issues/12#issue-476491788
![particiones del disco estado inicial](https://user-images.githubusercontent.com/51505710/62419773-c5b08c00-b688-11e9-90c0-154bea1a146c.jpg)
Repasemos las diferentes particiones:
-La partición de 500 mbs es nuestra partición de arranque su punto de montaje es: /boot/efi
-La partición de 15 gbs, es donde se guardarán nuestros saves de los juegos, su punto de montaje es: /home
-La partición de 60 gbs, es donde se va a instalar el sistema operativo, su punto de montaje es: /
-La partición de 1750 gbs (1,75tb) , es donde se van a copiar los packs de juegos, su punto de montaje es: /opt/systems. En el casillero no existe esta opción, la escribimos nosotros a mano.
Tener en cuenta que es un ejemplo con un disco duro de 2 TB, extrapolarlo a la capacidad de vuestro disco duro. Ahora os pongo unas capturas de lo explicado sobre los puntos de montaje:
![establezco los 500 mbs como bot-efi](https://user-images.githubusercontent.com/51505710/62419840-bc73ef00-b689-11e9-9c7c-a49cd5059daf.jpg)
![establezco particion de 15 gbs como home](https://user-images.githubusercontent.com/51505710/62419846-cd246500-b689-11e9-991f-4e71524c383f.jpg)
![establezco particion 60 gbs como raiz](https://user-images.githubusercontent.com/51505710/62419849-de6d7180-b689-11e9-96a7-ff07b969e4c0.jpg)
![establezo el resto del espacio como opt-systems](https://user-images.githubusercontent.com/51505710/62419852-efb67e00-b689-11e9-9e1e-a4a60a449c58.jpg)
Y cuando tenemos todos los puntos de montaje establecidos, podemos pulsar en el boton siguiente, y nos pregunta si queremos instalar en este punto:
![instalar usando este punto de restauracion](https://user-images.githubusercontent.com/51505710/62419861-22f90d00-b68a-11e9-9263-0b398bd3a240.jpg)
Confirmamos y comienza la instalación:
![instalando el sistema](https://user-images.githubusercontent.com/51505710/62419869-40c67200-b68a-11e9-8051-1639573910ef.jpg)
Cuando termine el proceso, nos muestra el siguiente mensaje:
![instalacion del sistema completado](https://user-images.githubusercontent.com/51505710/62419876-5f2c6d80-b68a-11e9-877c-fea9152f53f3.jpg)
Al pulsar en ok , nos devuelve al escritorio, donde tenemos un icono para apagar el sistema:
![apagar pc](https://user-images.githubusercontent.com/51505710/62419883-7ff4c300-b68a-11e9-9d04-a40da4ef6612.jpg)
Apagamos el Pc, desconectamos nuestro cable hdmi, o el que usemos para la instalación.Ya podemos conectar nuestro cable del PC a la tv o monitor. Y tenemos nuestro RGBuX instalado!!.

**Comment by DSkywalk** [comment]
pasado a la wiki:
https://github.com/rgb-x/system/wiki/Guia-de-Instalaci%C3%B3n-(es)
