### ISSUE TITLE
Rutas usadas en RGB-uX

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#14]
/opt/sytems = Carpetas de Juegos

/etc/emulationstation/es_systems.cfg = Archivo de configuración de EmulationStation. Aquí podemos configurar el emulador o core con el que van a ser lanzados, los juegos las extensiones de archivo a buscar, como se va a nombrar el  sistema dentro de ES.

/usr/games = Archivos ejecutables de por el ejemplo los emuladores de PS2 y PSP.

/opt/retroarch/configs/cores/ = Aquí podemos editar la configuración de cada core de forma individualizada.

/opt/RGBux/bin/15khz-switchres-exec = Este es la ubicación del generador de modelines de  RGBuX, nos sirve para poder generar modelines en tiempo real. Muy útil para lanzar juegos de wine, por ejemplo.

**Comment by DSkywalk** [comment]
ahora en https://github.com/rgb-x/system/wiki
