### ISSUE TITLE
Crear un archivo de configuración para un core. Gestion de los controles.

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#16]
Se debe crear un archivo .cfg que se tiene que copiar en la carpeta:  /op/retroarch/configs/cores
para psx  (por ejemplo) , el archivo se llamaria: pcsx_rearmed_libretro.cfg
y os pongo un ejemplo de como seria:
# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line

crt_switch_resolution = "1"
crt_switch_resolution_super = "0"
video_font_size = 12

input_player1_a = "a"
input_player1_a_btn = "0"
input_player1_b = "z"
input_player1_b_btn = "1"
input_player1_l = "q"
input_player1_l_btn = "4"
input_player1_r = "w"
input_player1_r_btn = "5"
input_player1_select = "rshift"
input_player1_select_btn = "6"
input_player1_start = "enter"
input_player1_start_btn = "7"
input_player1_x = "s"
input_player1_x_btn = "2"
input_player1_y = "a"
input_player1_y_btn = "3"

#include "/opt/retroarch/configs/ra-main.cfg"

desde este archivo de configuración podemos decirle a retroarch que use , o no las resoluciones dinamicas, y podemos asignar manualmente los controles
Para orientarnos en que boton del mando debemos asignar como se puede ver, cada acción tiene asignada una tecla, y a continuación un boton. La tecla nos sirve de referencia.Por ejemplo el boton A, tiene asignada la tecla a del teclado. Si durante el juego entramos a las  opciones de retroarch en  settings:
![01](https://user-images.githubusercontent.com/51505710/63371931-55428400-c385-11e9-910d-972a8bf438d7.jpg)
Luego buscamos la opcion input:
![02](https://user-images.githubusercontent.com/51505710/63371978-6db29e80-c385-11e9-8f4d-e422500f7407.jpg)
y dentro de input user 1 binds:
![03](https://user-images.githubusercontent.com/51505710/63372009-828f3200-c385-11e9-9779-3bc40989e220.jpg)
Aqui vemos como para el boton B tenemos afsignada la tecla "z" y además un botón. Bien pues esta asignación al teclado es la que nos sirve de referencia, para luego asignar el boton que queremos.
A continuación pulsamos para asignar un boton, tener en cuenta que hay que dejar apretado durante unos segundos:
![05](https://user-images.githubusercontent.com/51505710/63372141-d437bc80-c385-11e9-99b0-dc77ed159409.jpg)
Bien hemos puesto el boton que queriamos. Podemos volver al juego y probar si realmente funciona. Pero no se van a guardar los cambios. Solo se guardarán si modificamos nuestro archivo de configuración.nuestro archivo de personalizacion del core, se antepondra a la configuración general del retroarch.

**Comment by DSkywalk** [comment]
ahora en https://github.com/rgb-x/system/wiki/Crear-un-archivo-de-configuraci%C3%B3n-para-un-core.-Gestion-de-los-controles-(es)
