### ISSUE TITLE
Fallo en juegos de sega Naomi y Atomiswave. Cambio de core a Flyscast.

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#17]
Los juegos de naomi y atomiswave se congelan, al poco tiempo de arrancarlos. Este fallo es motivado por el core Flycast winCE. Hay que cambiar el core a Flycast.
Para ello abrimos retroarch, entramos a las opciones, y buscamos online updater:
![01](https://user-images.githubusercontent.com/51505710/63369510-6b9a1100-c380-11e9-96d4-3cbd261e6763.jpg)
A continuación le damos a update info core files:
![02](https://user-images.githubusercontent.com/51505710/63369602-8ec4c080-c380-11e9-81d4-d297d1eaac55.jpg)
Y despues le vamos a dar a update core, y nos saldrá una lista, escogemos SEGA Flycast:
![03](https://user-images.githubusercontent.com/51505710/63369681-be73c880-c380-11e9-86da-6423a194ee43.jpg)
 Bien, esto ya lo tenemos, pero ahora queremos que Emulation Station nos abra todos los juegos de dreamcast, de sega naomi y atomiswave con nuestro core Flycast.
Para ello debemos editar el famoso fichero es_systems.cfg que se encuentra en  la ruta: /etc/emulationstation:
![04](https://user-images.githubusercontent.com/51505710/63369864-29250400-c381-11e9-9e4c-2c7b90452d0a.PNG)
Si editamos este archivo, con mousepad , por ejemplo. Yo lo hago en red con wincsp, porque es mas comodo tenemos que llegar a estas lineas:
 ```  <system>
        <name>naomi</name>
        <fullname>Naomi</fullname>
        <path>/opt/systems/naomi/roms</path>
        <extension>.lst .zip .ZIP .chd</extension>
        <command>/opt/RGBux/frontend/launchers/lanzadorRA.sh -L /opt/retroarch/cores/flycast_wince_libretro.so %ROM%</command>
        <platform>naomi</platform>
        <theme>naomi</theme>
    </system>
Asi es como esta originalmente. Y lo tenemos que dejar asi:
   <system>
        <name>naomi</name>
        <fullname>Naomi</fullname>
        <path>/opt/systems/naomi/roms</path>
        <extension>.lst .zip .ZIP .chd</extension>
        <command>/opt/RGBux/frontend/launchers/lanzadorRA.sh -L /opt/retroarch/cores/flycast_libretro.so %ROM%</command>
        <platform>naomi</platform>
        <theme>naomi</theme>
    </system>
Lo mismo para Atomiswave:
    <system>
        <name>atomiswave</name>
        <fullname>Atomiswave</fullname>
        <path>/opt/systems/atomiswave/roms</path>
        <extension>.lst .zip .ZIP</extension>
        <command>/opt/RGBux/frontend/launchers/lanzadorRA.sh -L /opt/retroarch/cores/flycast_libretro.so %ROM%</command>
        <platform>atomiswave</platform>
        <theme>atomiswave</theme>
    </system>
Y por ultimo para sega dreamcast:
   <system>
        <name>dreamcast</name>
        <fullname>Dreamcast</fullname>
        <path>/opt/systems/dreamcast/roms</path>
        <extension>.zip .ZIP .cdi .CDI .gdi .GDI .chd .CHD</extension>
        <command>/opt/RGBux/frontend/launchers/lanzadorRA.sh -L /opt/retroarch/cores/flycast_libretro.so %ROM%</command>
        <platform>dreamcast</platform>
        <theme>dreamcast</theme>
    </system>

**Comment by DSkywalk** [comment]
fixed on rc5
