### ISSUE TITLE
Desactivar salvapantallas en RGBUX

### ISSUE THREAD

**Issue by sirmagb00** [rgb-x/system#18]
El salvapantallas está configurado por defecto en RGB-ux para que entre a los 10 minutos de inactividad. Para desactivarlo, salimos de Emulation Station, para regresar a nuestro escritorio. Desde aqui pulsamos el boton de inicio, y seleccionacos configuración y salvapantallas:
![01](https://user-images.githubusercontent.com/51505710/63374882-0566bb80-c38b-11e9-9969-21fbf26932d6.jpg)
Podemos ver como se activa a los 10 minutos:
![02](https://user-images.githubusercontent.com/51505710/63374912-10b9e700-c38b-11e9-8ff0-3691b9255370.jpg)
Desde la primera pestaña de arriba, podemos desactivarlo, que es lo suyo:
![03](https://user-images.githubusercontent.com/51505710/63374955-20d1c680-c38b-11e9-94bb-f7274eceecf3.jpg)
Y listo, ya no, va a molestar más.

**Comment by DSkywalk** [comment]
fixed on rc5
