### ISSUE TITLE
yavi rc1a - test 1

### ISSUE THREAD

**Issue by DSkywalk** [rgb-x/system#2]
- [x] el pygame le renderiza mal (y a sirmagb tambien?)
- [ ] dos tarjetas de red, tiene que quitar una de network/interfaces para que le funcione samba.
- [ ]

**Comment by DSkywalk** [comment]
@yavimaya se que no se te ve en el entorno de red RGBux por las dos tarjetas, pero tras iniciar sin tocar nada:
¿puedes acceder a samba directamente poniendo **\\\\IP** en tu explorador de windows?
(cambiando IP por tu ip actual)

**Comment by sirmagb00** [comment]
El menu de opciones dentro de ES , (pygame) , ya es funcional. Con la versión RC2 los juegos no salen con su resolución y se descentran mucho, solo los juegos de amstrad CPC se muestran correctamente.
