### ISSUE TITLE
Posible solución al problema del entrelazado con kernels mayores a 4.19

### ISSUE THREAD

**Issue by webodan** [rgb-x/system#21]
Vaya por delante que no sé programar, pero le he echado un ojo al problema y estas son las ideas que se me ocurren para reparar el problema de que el vídeo en entrelazado 15khz usando rgbux con un kernel superior a 4.19 funcione a 30 hz:

1 - (solución adecuada) Revertir los cambios del código del kernel 4.20 que hayan hecho en los drivers de vídeo (amdgpu y/o radeon) que afecten al vídeo entrelazado, y lanzar parches o un kernel enteramente parcheado que integre los cambios. Echando un ojo, yo creo que la idea sería revertir a los cambios que hay en las carpetas [drivers/gpu/drm/amd](https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/amd) y/o [drivers/gpu/drm/radeon](https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/radeon) del kernel.

2 - (solución guarra, hay que probarla pero igual tira) Copiar los drivers amdgpu y radeon (cualquiera que sea que use la distro) del kernel 4.19 en rgbux con un kernel más moderno. Al estar compilados, al menos en teoría, no debería de tener problemas de usar un driver distinto (que no lo sé, pero es lo que se me ocurre probar).

Los drivers a copiar serían /lib/modules/(versión del kernel 4.19 o anterior)/gpu/drm/amd/amdgpu/amdgpu.ko.xz ,  y  /lib/modules/(versión del kernel 4.19 o anterior)/gpu/drm/radeon/radeon.ko.xz

No tengo máquinas que puedan tirar rgbux para probar cualquiera de las dos soluciones, pero yo dejo la idea en el aire para cuando se pueda implementar, ahí no se pierda.

Dejo por aquí unos enlaces que puedan ayudar a encontrar los cambios en el código para implementar, posiblemente, la solución nº 1:

[Changelog del kernel 4.20](https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.20)

[Otro changelog detallado](https://kernelnewbies.org/Linux_4.20)

Si puede alguien probar la solución nº 2 para descartarla también estaría bien.

**Comment by DSkywalk** [comment]
Pero si el kernel 5.x funciona perfectamente el entrelazado :?

no entiendo esta issue...

**Comment by webodan** [comment]
ah mierda, es que me dice el sirmagb que no va bien por el telegram

**Comment by DSkywalk** [comment]
np
