### ISSUE TITLE
[bug] CPU Scaling governor

### ISSUE THREAD

**Issue by yavimaya** [rgb-x/system#24]
Parece que se está estableciendo el governor como "auto", pero las opciones válidas para éste son:

- Schedutil (Por defecto, ha estado incorporado desde el kernel 4.7 al kenel 4.18)

Ya que aprovecha los datos de utilización del planificador del núcleo en un intento de tomar mejores decisiones sobre el ajuste del estado de frecuencia / rendimiento del CPU.

- Performance

El regulador de rendimiento esta empotrado en el núcleo y hace que las UCP funcionen a la máxima velocidad de reloj.

- Ondemand (recomendado para AMD)

Incrementa/Decrementa dinámicamente la velocidad de reloj de la UCP en base a la carga del sistema.

- Conservative

Similar a ondemand, pero más conservador (los cambios de velocidad son más suaves)

- Powersave

Hacer funcionar la UPC a la velocidad mínima.

- Userspace

Velocidades de reloj configuradas manualmente por el usuario.

He instalado el cpufrequtils para ver las opciones de governor en mi cpu (i5 6400)  y veo que solo se pueden setear como governor los valores Performance o Powersave. Desconozco si para otras cpu se puden otros valores. Esta información la he obtenido mediante el comando: `cpupower frequency-info
`

**Comment by DSkywalk** [comment]
gracias por el reporte.

El cambio que propongo es que si está seteado como auto (que es como por defecto se configura al iniciar el sistema), simplemente salir del script.

**Comment by DSkywalk** [comment]
fixed on rc6

**Comment by DSkywalk** [comment]
dejo abierto hasta que salga la rc6 públicamente, mejor.
