### ISSUE TITLE
Include en ra-main.cfg incorrecto

### ISSUE THREAD

**Issue by yavimaya** [rgb-x/system#26]
En los includes del final del fichero /opt/retroarch/configs/ra-main.cfg hay uno que no es correcto:
- #include "/opt/retroarch/configs/ra-menu-ctrl.cfg"

Debería cambiarse por: 
- #include "/opt/retroarch/configs/ra-controls-menu.cfg"

**Comment by DSkywalk** [comment]
fixed! gracias Yavi!
