### ISSUE TITLE
Ejecución de cores por primera vez e imagen a pantalla partida

### ISSUE THREAD

**Issue by yavimaya** [rgb-x/system#28]
Me he dado cuenta que al ejecutar por pimera vez cores de NES, a parte del messen_libretro.so, en el fichero /opt/retroarch/configs/retroarch-core-options.cfg se crean unas lineas por cada core ejecutado. 
Por ejemplo, al ejecutar fceumm_libretro.so, unas de las lineas creadas en el cfg anterior es `fceumm_overscan_v = "enabled"`.
Esto hace que la imagen solo salga en media pantalla.
Para solucionarlo simplementa hay que establecer `fceumm_overscan_v = "disabled"`.

Por lo tanto si se ejecutan nuevos cores y se ve imagen solo en media pantalla, revisar estas lineas.

No se si es un fallo de este sistema o de RA, pero por si acaso aqui lo dejo.

**Comment by DSkywalk** [comment]
gracias, solucionado :)
