### ISSUE TITLE
Pruebas con RC1

### ISSUE THREAD

**Issue by jaalmagro** [rgb-x/system#4]
Los emuladores bajo retroarch, que supongo serán todos menos groovy,  me funcionan correctamente excepto que la imagen produce un barrido vertical. Cambiando la opción en retroarch/settings/video/crt switchres/X-axis centering, a -1, -2, -3 se mantiene estable.  En mi caso, parece que -3 es el valor mejor, más centrado.

**Comment by DSkywalk** [comment]
en resolucion native? prueba a entrar desde ssh/samba y cambia de native (0) a dinamic (1) y comentame si sigues necesitando el centrado de x. Gracias!

/opt/retroarch/configs/ra-main.cfg

**Comment by DSkywalk** [comment]
Recuerdo que comentaste que no tenías red: 
PULSA CTRL+ALT+F3 y desde la consola lo puedes cambiar.

**Comment by jaalmagro** [comment]
El problema es q no tengo red en la máquina. Uso un pincho usb/wifi que no se configura automáticamente. Puedo tocar directamente el fichero desde el escritorio, no? Y luego probar

**Comment by DSkywalk** [comment]
Si, desde el escritorio saliendo de ES. O como te he comentado sin salir de ES, pulsando C+A+F3/F4...

**Comment by jaalmagro** [comment]
Jaja, ok. Me he solapado en la respuesta contigo.
