### ISSUE TITLE
test rc3

### ISSUE THREAD

**Issue by DSkywalk** [rgb-x/system#6]
## AÑADIDO
* Eliminado cursor raton en modos game/fe y añadido bg.
* motd modificado con intro de RGBux y alguna info de debug.
* cambiando TODO el sistema de scripts de nuevo para facilitar hacer scripts en ES.
* la config de mame ahora está en /etc/mame y el usuario puede añadir solo los cambios que desee en su HOME.
* añadido a /opt/RGBux un directorio llamado autostart que se ejecuta al iniciar el sistema (antes de las X)
* eliminadas opciones de openbox y resuelto un pequeño bug (aunque seguramente se elimine todo).
* menu/configure: port - ahora se puede configurar desde ES.
* menu/configure: monitor - ahora se puede configurar desde ES.
* menu/configure: governor -  ahora se puede configurar desde ES y usa autostart para setear al inicio.
* menu/configure: boot - ahora se puede configurar desde ES.
* menu/retroarch: super-resolution - ahora se puede configurar desde ES.
* ahora el boot-game se inicia desde */opt/systems/boot-game.sh* si existe. 
* he vuelto a dejar VGA/24 por que daba problemas con WINE.
... y más cosas que ni recuerdo xd

## SOFTWARE
* actualizado RA a 1.7.7 (pero sigo manteniendo 1.7.6 en la iso se puede cambiar con un ln)
* recompilado GA para permitir /etc/mame.
* probando nes con mesen.
* probando snes con bsnes_balanced.
* recompilado kernel 4.15.x con un pequeño fix que esperemos que resuelva la mayoría de problemas con el modo entrelazado.

## FALLOS CONOCIDOS:

* [x] RA no guarda los saves en la carpeta de usuario. Lo sigue haciendo donde está la rom.
* [ ] Los controles no se pueden configurar. (por el momento usamos los autoconfigs ¿tutorial para crearlos?)
* [x] menu: port - cambiar el conector no cambia el grub! **arreglado rc3a**
* [x] menu: configure : el mando no responde bien (usad teclado). **arreglado rc3a**
* [x] estaría bien mover ra/configs/all/retroarch.cfg a etc. **arreglado rc3a**
* [x] ra1.7.7 - estaria bien tener el debug modeline igual que en 1.7.6 **arreglado rc3a**
* [x] tener un menu que te diga la ip y reinicie la red.
* [ ] cuando synaptic intenta usar pkexec (y petan todas las x), habría que arreglar el pkexec.
* [ ] no se pueden montar unidades externas.

## WONT FIX
* modo tate/vertical.
* ra1.7.7 - los mensajes no se ven bien.

#### menores
añadido sudo en los helpers
system_init añadido replace_mame
ra-saves estaba duplicado con ra-init

**Comment by DSkywalk** [comment]
Dejad vuestros resultados como nuevos comentarios en esta misma ISSUE.

## TESTERS

* [x] @sirmagb00 
* [x] yavimaya
* [x] @sistemaoctal
* [ ] Theboy995
* [ ] nelet87
* [ ] @Sidecar940
* [x] Carlo
* [x] Rui Orey
* [x] Jcyrydia
* [x] Ivan C.G.

# FALLOS A SOLUCIONAR

* [x] añadir "trap" para groovymame (thx Carlo). **arreglado rc3b**
* [x] a 31Khz inicia ES y no mueve los iconos (thx sirmagb). **arreglado rc3b**
* [x] DVI-I-1 inicia a 31Khz (sirmagb) **arreglado rc3b**
* [x] Ivan, tiene DVI-D-1 y DVI-I-1 (y ambos los detecta como DVI-0) **arreglado rc3c**
* [x] sirmagb, tiene DVI-D-1 y DVI-I-1 (y los tiene en un orden diferente) **arreglado en rc3d**
* [x] retroarch save/states no se guardan en $HOME **arreglado en rc3e**
* [ ] alguna tarjeta antigua a veces genera modos arcade en puertos deshabitados **arreglado rc3f**

# PRUEBAS A REALIZAR EN LA RC3

*Iniciad la prueba con el cable de red puesto si teneis pensado pasar juegos usando samba.*
*Todo lo que cambiéis en el sistema se hace en RAM, por tanto al reiniciar se pierden los cambios.*

1. Arrancad en modo 31Khz y comprobad que os salen los iconos de Instalar y apagar. Comprobad que podéis instalar sin tener que poner el nombre de usuario. Y **no instaléis** entre otras cosas por que no funciona la instalación AÚN. Si no tenéis monitor 31Khz a mano o la máquina inicia a 15Khz directa. Pasad de este punto e id directos al 2º.

2. Arrancad en modo 15Khz con la config de vuestro sistema (VGA/DVI).
2.1 Lo primero que aparecerá es mame, probad como va y luego si teneis red pasad un par de juegos por red y comprobad desde ES que funcionan bien otros juegos de mame.

3. Testead emuladores y los que os den problemas en la TV vais al nuevo menu de RGBux y cambiad las opciones del tipo de monitor (configure/monitor) o probad a cambiar de super-resolucion (retroarch/super-resolution), y cread una ISSUE con vuestras pruebas aquí.

### OTRAS PRUEBAS QUIZÁ MÁS COMPLEJAS

* COMPROBAD el modo entrelazado, emuladores y wine.
* COMPROBAD que mame SI guarda los records con la nueva CFG. Pasad alguna rom con hiscore, como el gng/sfce/...
* Como prueba: bsnes y cap32 están forzados a usar resolución nativa. Lo podéis cambiar en /opt/retroarch/configs/cores/ y veréis las configs con el mismo nombre que el core.

Tened en cuenta que los juegos que pasáis a la LIVE se guardan en RAM, entonces no paséis roms muy gordas o petará.

Con las pruebas y arreglos de esta RC3, sacaremos la primera versión pública con el installer funcional:
# será la **BETA1**, GRACIAS A TODOS! :tada:

**Comment by sistemaoctal** [comment]
rc3c
1) menu inicial (a la hora de elegir el puerto de la vga 15khz),con puertos dvi cambiados, el 1 que es el analogico , solo funciona si eliges  el 2º dvi , pero solo funciona el mame inicial 
2) vuelve la falta de vsync ,mas acentuada que en 2/3 versiones atras (mame vrally).
ES (al salir con escape del vrally),fuera de sincronía

**Comment by sistemaoctal** [comment]
RC3E
1ero 
en mame vsync parece correcto, controles configurables y funcionales
2º
* en Es se configuran los controles y parecen funcionar en todos los emuladores 
* emu de ps2 parece no instalado, no he podido instalarlo desde la consola m aunque con apt-get install  lo intenta y pide permiso para hacerlo ,pero falla, total que en ES ,pese a tener las bios en la carpeta de bios de retroarch , se sale otra vea a ES tras hacer el intento de cargar juego (ps2 no tiene theme en ES sale sin logo ni nombre , solo lista de juegos una vez coipados y reiniciado ES)
* game gear, sale a pantalla completa de inicia , horrible, se ve fatal tan grande, arreglable en menu retroach con f1, pero .... (siguiente punto)
* la master system no se ve bien, la master system tenia marcos en ambos lados,no llenaba pantalla(bueno si m ero con un color, vease sonic 2  por ejemplo)no hay manera de ponerlo como deberia de verse, con franjas (o de color o negras en su defecto) arrioba abajo y a los lados, porque aun en ntsc ,deberia de verse franjas arriba y abajo por la resolucion, en pal mas grandes, pero en ntsc hay marcos en los 4 lados)imagino que cambiando el core y usando uno distinto al de game gear se solucione o se configure mejor independientemente
*megadrive creo recordar que parecia ir bien(solo testeada rom de prueba)
*nes (solo testeada rom de pruebam no se si hay tearing porque el juego no tiene scroll)
*gamecube se me colgó el emu(que no es sistema (con una rom que me hace lo mismo en rgbx, osea qeu no es fallo del emu ni de rgbux, sino la rom, pero no pude cerrar retroarch sin reiniciar y perder los cambios y ya no pude seguir con las pruebas para recordar apuntarlo todo, no tenia boli a mano XD)
* snes se ve 1/4 de la pantalla, no probé cambiarlo con f1, pensé hacerlo tras meter mas roms, pero probé el de gamecube y se me fue a la merd,como explico en el * anterior.

**Comment by sirmagb00** [comment]
Probando la R3F. Añadido el modulo de comprobación de la IP, todavia no es funcional, aunque ya esta solucionado, para la siguiente versión. Realizo las pruebas en todos los sistemas, son satisfactorias (en cuanto a que todos funcionan y en cuanto al centrado de juegos, teniendo en cuenta las limitaciones de los emuladores). Mi tarjeta actualmente es una ATI R9 270. 
Cambio la tarjeta a una gráfica NVIDIA GTX 550 TI. El sistema configura correctamente el puerto.Se nota overscan dentro de ES, pero en los juegos la resolución es la correcta.Funciona perfectamente con los sistemas incluidos en la versión live: Master System,Game Gear,Megadrive, Nes,Super Nes,Zx spectrum, Amiga, y amstrad CPC. El unico fallo que percibo, es que cuando sales de un juego de RA , al volver a la resolución que usa el ES, con el tema "Retrorama", a veces se ven cosas extrañas, como dejar de ver los titulos de los juegos. He probado cambiado al tema carbon, y no sucede este fallo.
Cambio a la siguiente tarjeta, una GTX 750 Ti.Pero la tarjeta no funciona correctamente, tarjeta china de aliexpress, y rehuso hacer la prueba.

**Comment by DSkywalk** [comment]
Inicio RC4
