### ISSUE TITLE
LIVE/INSTALL - team test

### ISSUE THREAD

**Issue by DSkywalk** [rgb-x/system#8]
# Fallos conocidos / Known BUGS
- [ ] La red no inicia tras instalar / No LAN after INSTALL (ver [fix temporal](https://github.com/rgb-x/system/issues/10))

# Mejoras pendientes
- [ ] añadir HDMI-A-0,  HDMI-A-1 a xorg.
- [ ] añadir */opt/systems* a systemback.

# Fallos corregidos
- [x] Añadir [packages](https://github.com/rgb-x/system/wiki/Install-Packages) para desde consola instalar: kodi, wine,...
- [x] mame configure: freeplay, continue, savestates, ...
- [x] añadido CHD en PSX.
- [x] grub no se actualiza, quizá falta llamar a update-grub antes de lanzar el installer.
  - he probado a sobrescribir el grub.cfg y tampoco va... No se que cojones hace. miraré el codigo.
- [x] añadir DisplayPort-0/1 a xorg

**Comment by DSkywalk** [comment]
# Fixes temporales

## La red no inicia

- `ifconfig -a` fíjate como se llama tu tarjeta de red (suele empezar por **enp..**)
- entra como root y edita el fichero /etc/network/interfaces
- y edita el segundo `auto eth0` y cambialo por el nombre de tu interfaz de red. Ej: si fuera **enp6s0**, quedaría así...
![imagen](https://user-images.githubusercontent.com/560310/61589359-07c9d000-aba9-11e9-8d5c-30b3806a88b1.png)

**Comment by sirmagb00** [comment]
Es necesario añadir las extensiones .chd  y . CHD a la plataforma PSX, ya que nuestro packs hacen uso de estos ficheros. Así pues es necesario editar el fichero es_systems.cfg

**Comment by sirmagb00** [comment]
En Psx, el boton start y en ocasiones las direcciones , no funcionan en los juegos, si se intenta reconfigurar, desde settings, tampoco obedece. He probado con dos mandos diferentes, xbox 360 y PS4, con ambos el resultado es el mismo. Es imposible poder iniciar un juego,o bien por fallo del start, o por que las direcciones tampoco responden. En el menu se puede intercambiar entre control standar y control dual shock , asi como analog. He probado en todas las opciones disponibles.

**Comment by sirmagb00** [comment]
El fallo de los controles en PSX, es por falta de updatear el core. Desde online updater, update info core file. Despues update de pcsx reamed, y por ultimo update de los assets. Y a funcionar.

**Comment by sirmagb00** [comment]
Probando el juego Sonic Mania de wine, y dejando el juego sin tocar ninguna tecla o boton del joystick, a los 15 minutos, salta el salvapantallas. Es necesario revisar las opciones de energia del sistema.

--
*/5 * * * * /usr/bin/env DISPLAY=:0.0 xset -dpms
xset -display :0 dpms force [on/off]

--
xset -display :0 s noblank		# Screen Saver:			prefer blanking:  no    allow exposures:  yes
xset -display :0 s off			# DPMS (Energy Star):	Standby: 0	Suspend: 0    Off: 0
xset -display :0 -dpms			# DPMS (Energy Star):	DPMS is Disabled
xset -display :0 s 0 0			# Screen Saver:			timeout:  0    cycle:  0
xset -display :0 dpms 0 0 0		# DPMS (Energy Star):	DPMS is Enabled	Monitor is On

xset -display :0 dpms force off	# Now screen saver is on, but screen is a fine checkered gray pattern
xset -display :0 dpms force on	# Now screen saver is off, i.e. back to normal screen.

**Comment by sirmagb00** [comment]
Prueba de sistemas: Colocando roms tanto en mame, como en fba verticales, ES no las reconoce, y en FBA en la carpeta NEO GEO,tampoco son reconocidas las roms. Sega Naomi y Atomiswave, salen con la pantalla desplazada hacia la izquierda, se crea una banda lateral a  la derecha de un par de dedos.En dreamcast tambien sucede, es decir que es algo del core Flycast. En dreamcast, tambien he puesto un juego en la carpeta arcade, y tampoco ha sido reconocido por ES. He instalado ppsspp, y su funcionamiento es muy bueno, no existe launcher para este sistema. He vuelto a probar el core en RA, y sigue quedandose en pantalla negra.NEO GEO CD, he colocado las roms, pero dentro de la carpeta neocdz, aun asi no son reconocidos los juegos, debe de haber alguna ruta mal.
Otros sistemas probados y funcionando correctamente: Sega 32x, Nintendo 64, Nitendo FDS, y Nintendo Game Cube,Pc Engine CD,Pc Engine.

**Comment by sirmagb00** [comment]
### Como recuperar la red, tras la instalación de RGBux. 

En primer lugar salir de Emulation Station, normalmente es el botón start del mando , o la tecla ENTER del teclado, debemos pulsar en “quit emulation station”. Saldremos a un escritorio, donde en la esquina inferior izquierda, tenemos un botón de inicio, lo pulsamos y abrimos un emulador de terminal, donde tecleamos lo siguiente:
sudo ifconfig –a
![image](https://user-images.githubusercontent.com/51505710/62415488-b0a51000-b62a-11e9-85af-a208f3a90c7e.png)
Observamos que nuestra tarjeta de red tiene el nombre de enp6s0, en tu caso cambiará será algo parecido.
a continuación tecleamos:
sudo su -
mc /etc/network
edita el fichero interfaces (pulsa F4)

![image](https://user-images.githubusercontent.com/51505710/62415499-e0541800-b62a-11e9-9d2b-feed84bd2617.png)
ves el segundo auto eth0?
descomenta esa linea y la de abajo
y cambia eth0 por "enp6s0" (cambia enp6s0 por el nombre de tu tarjeta de red)
debe quedar asi:
![image](https://user-images.githubusercontent.com/51505710/62415514-109bb680-b62b-11e9-9223-4b15c0375172.png)
Ahora ,f10 sal y guarda y reinicia ,a ver si ya lo tienes
sudo reboot, si quieres reiniciar rapido
